[package]
name = "toroxyproxy"
version = "0.1.0"
authors = ["D Keeler <mozkeeler@gmail.com>"]

[dependencies]
byteorder = "1.2.1"
toroxide = { path = "../toroxide" }
toroxide-openssl = { path = "../toroxide-openssl" }
